# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', python: 'pypy3.9'}
          - {os: macOS-latest, r: 'release', python: 'pypy3.9'}
          - {os: ubuntu-latest, r: 'release', python: 'pypy3.9'}
          - {os: ubuntu-latest, r: 'devel', python: 'pypy3.9'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.config.python }}
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.config.python }}

      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra-packages: any::rcmdcheck

      - run: |
           python -m pip install virtualenv sudachipy sudachidict_core

      - uses: r-lib/actions/check-r-package@v2
        env:
          RETICULATE_PYTHON: ${{ steps.setup-python.outputs.python-path }}
        with:
          error-on: '"error"'
